AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Exclude:
    - "gemfiles/**/*"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/FrozenStringLiteralComment:
  Exclude:
    - "gemfiles/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
