AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Exclude:
    - "gemfiles/**/*"

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Style/FrozenStringLiteralComment:
  Exclude:
    - "gemfiles/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
