after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install: gem install bundler -v 2.0.2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

env:
  global:
    - CC_TEST_REPORTER_ID=91fd1b5f4e32e12f68c365516db8abff11ac17b75d043c7b18e672b836a92f15

gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_6_1.gemfile
  - gemfiles/rails_7_0.gemfile
  - gemfiles/latest.gemfile

language: ruby

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - 3.0.3

script:
  - bundle exec rspec
  - bundle exec rubocop
